// packages/blocks-vue/src/wishlist/WishlistButton.vue
<template>
  <button
    type="button"
    :class="['vkecom-wishlist-button', { 'in-wishlist': inWishlist }, className]"
    :aria-label="inWishlist ? inWishlistLabel : notInWishlistLabel"
    @click="handleClick"
  >
    <slot>
      {{ inWishlist ? inWishlistLabel : notInWishlistLabel }}
    </slot>
  </button>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useWishlist } from './useWishlist';
import type { Product } from '@vk/blocks-core';

interface Props {
  product: Product;
  className?: string;
  inWishlistLabel?: string;
  notInWishlistLabel?: string;
  onAdd?: (product: Product) => void;
  onRemove?: (productId: string) => void;
}

const props = withDefaults(defineProps<Props>(), {
  inWishlistLabel: 'Remove from Wishlist',
  notInWishlistLabel: 'Add to Wishlist',
});

const wishlist = useWishlist();
const inWishlist = computed(() => wishlist.hasProduct(props.product.id));

const handleClick = () => {
  if (inWishlist.value) {
    wishlist.removeProduct(props.product.id);
    props.onRemove?.(props.product.id);
  } else {
    wishlist.addItem(props.product);
    props.onAdd?.(props.product);
  }
};
</script>

// packages/blocks-angular/src/wishlist/wishlist-button.component.ts
/**
 * Wishlist button component
 */

import { Component, Input, Output, EventEmitter, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { WishlistService } from './wishlist.service';
import type { Product } from '@vk/blocks-core';

@Component({
  selector: 'vk-wishlist-button',
  standalone: true,
  imports: [CommonModule],
  template: `
    <button
      type="button"
      [class]="[
        'vkecom-wishlist-button',
        { 'in-wishlist': inWishlist() },
        className || ''
      ].join(' ')"
      [attr.aria-label]="inWishlist() ? inWishlistLabel : notInWishlistLabel"
      (click)="handleClick()"
    >
      {{ inWishlist() ? inWishlistLabel : notInWishlistLabel }}
    </button>
  `,
})
export class WishlistButtonComponent {
  @Input() product!: Product;
  @Input() className?: string;
  @Input() inWishlistLabel = 'Remove from Wishlist';
  @Input() notInWishlistLabel = 'Add to Wishlist';
  @Output() add = new EventEmitter<Product>();
  @Output() remove = new EventEmitter<string>();

  inWishlist = computed(() => this.wishlist.hasProduct(this.product.id));

  constructor(public wishlist: WishlistService) {}

  handleClick(): void {
    if (this.inWishlist()) {
      this.wishlist.removeProduct(this.product.id);
      this.remove.emit(this.product.id);
    } else {
      this.wishlist.addItem(this.product);
      this.add.emit(this.product);
    }
  }
}


<button
  type="button"
  [class]="[
    'vkecom-wishlist-button',
    { 'in-wishlist': inWishlist() },
    className || ''
  ].join(' ')"
  [attr.aria-label]="inWishlist() ? inWishlistLabel : notInWishlistLabel"
  (click)="handleClick()"
>
  {{ inWishlist() ? inWishlistLabel : notInWishlistLabel }}
</button>
