// packages/blocks-angular/src/components/cart-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import type { CartItem as CartItemType } from '@alejandrovrod/blocks-core';

/**
 * CartItem component - Displays a single cart item
 * Fully customizable via CSS classes
 */
@Component({
  selector: 'vk-cart-item',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './cart-item.component.html',
})
export class CartItemComponent {
  @Input() item!: CartItemType;
  @Input() className?: string;
  @Output() increase = new EventEmitter<string>();
  @Output() decrease = new EventEmitter<string>();
  @Output() remove = new EventEmitter<string>();

  onIncrease(): void {
    this.increase.emit(this.item.id);
  }

  onDecrease(): void {
    this.decrease.emit(this.item.id);
  }

  onRemove(): void {
    this.remove.emit(this.item.id);
  }

  formatPrice(price: number): string {
    return `$${price.toFixed(2)}`;
  }
}


<div
  [class]="'vkecom-cart-item ' + (className || '')"
  [attr.data-item-id]="item.id"
  itemscope
  itemtype="https://schema.org/Product"
>
  <div class="vkecom-cart-item-image">
    <img
      *ngIf="item.product.image"
      [src]="item.product.image"
      [alt]="item.product.name"
      loading="lazy"
      itemprop="image"
    />
    <div *ngIf="!item.product.image" class="vkecom-cart-item-image-placeholder">
      No image
    </div>
  </div>

  <div class="vkecom-cart-item-details">
    <h3 class="vkecom-cart-item-name" itemprop="name">
      {{ item.product.name }}
    </h3>
    <p
      *ngIf="item.product.description"
      class="vkecom-cart-item-description"
      itemprop="description"
    >
      {{ item.product.description }}
    </p>
    <div
      class="vkecom-cart-item-price"
      itemprop="offers"
      itemscope
      itemtype="https://schema.org/Offer"
    >
      <span class="vkecom-cart-item-price-unit">
        {{ '$' + formatPrice(item.product.price) }}
      </span>
      <span class="vkecom-cart-item-price-total">
        Total: {{ '$' + formatPrice(item.product.price * item.quantity) }}
      </span>
      <meta itemprop="price" [content]="item.product.price.toString()" />
      <meta itemprop="priceCurrency" content="USD" />
    </div>
  </div>

  <div class="vkecom-cart-item-quantity">
    <button
      type="button"
      class="vkecom-cart-item-quantity-decrease"
      (click)="onDecrease()"
      [attr.aria-label]="'Decrease quantity of ' + item.product.name"
    >
      -
    </button>
    <span
      class="vkecom-cart-item-quantity-value"
      [attr.aria-label]="'Quantity: ' + item.quantity"
    >
      {{ item.quantity }}
    </span>
    <button
      type="button"
      class="vkecom-cart-item-quantity-increase"
      (click)="onIncrease()"
      [attr.aria-label]="'Increase quantity of ' + item.product.name"
    >
      +
    </button>
  </div>

  <button
    type="button"
    class="vkecom-cart-item-remove"
    (click)="onRemove()"
    [attr.aria-label]="'Remove ' + item.product.name + ' from cart'"
  >
    Remove
  </button>
</div>

// packages/blocks-react/src/components/CartItem.tsx
import React from 'react';
import type { CartItem as CartItemType } from '@alejandrovrod/blocks-core';

export interface CartItemProps {
  item: CartItemType;
  className?: string;
  children?: React.ReactNode;
  renderImage?: (item: CartItemType) => React.ReactNode;
  renderTitle?: (item: CartItemType) => React.ReactNode;
  renderPrice?: (item: CartItemType) => React.ReactNode;
  renderQuantity?: (item: CartItemType, onIncrease: () => void, onDecrease: () => void) => React.ReactNode;
  renderRemove?: (item: CartItemType, onRemove: () => void) => React.ReactNode;
  onIncrease?: (itemId: string) => void;
  onDecrease?: (itemId: string) => void;
  onRemove?: (itemId: string) => void;
}

/**
 * CartItem component - Displays a single cart item
 * Fully customizable, no styles included
 * Uses logical CSS classes: vkecom-cart-item, vkecom-cart-item-image, etc.
 */
export function CartItem({
  item,
  className = '',
  children,
  renderImage,
  renderTitle,
  renderPrice,
  renderQuantity,
  renderRemove,
  onIncrease,
  onDecrease,
  onRemove,
}: CartItemProps) {
  const handleIncrease = () => {
    if (onIncrease) {
      onIncrease(item.id);
    }
  };

  const handleDecrease = () => {
    if (onDecrease) {
      onDecrease(item.id);
    }
  };

  const handleRemove = () => {
    if (onRemove) {
      onRemove(item.id);
    }
  };

  return (
    <div
      className={`vkecom-cart-item ${className}`}
      data-item-id={item.id}
      itemScope
      itemType="https://schema.org/Product"
    >
      {children ? (
        children
      ) : (
        <>
          <div className="vkecom-cart-item-image">
            {renderImage ? (
              renderImage(item)
            ) : item.product.image ? (
              <img
                src={item.product.image}
                alt={item.product.name}
                loading="lazy"
                itemProp="image"
              />
            ) : (
              <div className="vkecom-cart-item-image-placeholder">No image</div>
            )}
          </div>

          <div className="vkecom-cart-item-details">
            {renderTitle ? (
              renderTitle(item)
            ) : (
              <h3 className="vkecom-cart-item-name" itemProp="name">
                {item.product.name}
              </h3>
            )}

            {item.product.description && (
              <p className="vkecom-cart-item-description" itemProp="description">
                {item.product.description}
              </p>
            )}

            {renderPrice ? (
              renderPrice(item)
            ) : (
              <div
                className="vkecom-cart-item-price"
                itemProp="offers"
                itemScope
                itemType="https://schema.org/Offer"
              >
                <span className="vkecom-cart-item-price-unit">
                  ${item.product.price.toFixed(2)}
                </span>
                <span className="vkecom-cart-item-price-total">
                  Total: ${(item.product.price * item.quantity).toFixed(2)}
                </span>
                <meta itemProp="price" content={item.product.price.toString()} />
                <meta itemProp="priceCurrency" content="USD" />
              </div>
            )}
          </div>

          <div className="vkecom-cart-item-quantity">
            {renderQuantity ? (
              renderQuantity(item, handleIncrease, handleDecrease)
            ) : (
              <>
                <button
                  type="button"
                  className="vkecom-cart-item-quantity-decrease"
                  onClick={handleDecrease}
                  aria-label={`Decrease quantity of ${item.product.name}`}
                >
                  -
                </button>
                <span className="vkecom-cart-item-quantity-value" aria-label={`Quantity: ${item.quantity}`}>
                  {item.quantity}
                </span>
                <button
                  type="button"
                  className="vkecom-cart-item-quantity-increase"
                  onClick={handleIncrease}
                  aria-label={`Increase quantity of ${item.product.name}`}
                >
                  +
                </button>
              </>
            )}
          </div>

          {renderRemove ? (
            renderRemove(item, handleRemove)
          ) : (
            <button
              type="button"
              className="vkecom-cart-item-remove"
              onClick={handleRemove}
              aria-label={`Remove ${item.product.name} from cart`}
            >
              Remove
            </button>
          )}
        </>
      )}
    </div>
  );
}
