// packages/blocks-vue/src/checkout/CheckoutForm.vue
<template>
  <form :class="['vkecom-checkout-form', className]" @submit.prevent="handleSubmit">
    <div v-if="!renderFields" class="vkecom-checkout-shipping">
      <h3>Shipping Address</h3>
      <input
        v-model="shippingAddress.street"
        type="text"
        placeholder="Street"
        class="vkecom-checkout-field"
      />
      <input
        v-model="shippingAddress.city"
        type="text"
        placeholder="City"
        class="vkecom-checkout-field"
      />
      <input
        v-model="shippingAddress.postalCode"
        type="text"
        placeholder="Postal Code"
        class="vkecom-checkout-field"
      />
      <input
        v-model="shippingAddress.country"
        type="text"
        placeholder="Country"
        class="vkecom-checkout-field"
      />
    </div>

    <label v-if="!renderFields" class="vkecom-checkout-same-address">
      <input v-model="useSameAddress" type="checkbox" />
      Use same address for billing
    </label>

    <div v-if="!useSameAddress && !renderFields" class="vkecom-checkout-billing">
      <h3>Billing Address</h3>
      <input
        v-model="billingAddress.street"
        type="text"
        placeholder="Street"
        class="vkecom-checkout-field"
      />
      <input
        v-model="billingAddress.city"
        type="text"
        placeholder="City"
        class="vkecom-checkout-field"
      />
      <input
        v-model="billingAddress.postalCode"
        type="text"
        placeholder="Postal Code"
        class="vkecom-checkout-field"
      />
    </div>

    <div v-if="!renderFields" class="vkecom-checkout-payment">
      <h3>Payment Method</h3>
      <select v-model="paymentMethod.method" class="vkecom-checkout-field">
        <option value="">Select payment method</option>
        <option value="credit_card">Credit Card</option>
        <option value="debit_card">Debit Card</option>
        <option value="mercado_pago">Mercado Pago</option>
      </select>
    </div>

    <slot name="fields" :shipping-address="shippingAddress" :billing-address="billingAddress" :payment-method="paymentMethod" :on-shipping-change="handleShippingChange" :on-billing-change="handleBillingChange" :on-payment-change="handlePaymentChange" />

    <button
      v-if="!renderSubmit"
      type="submit"
      :disabled="checkout.loading || !checkout.session || checkout.status !== 'pending'"
      class="vkecom-checkout-submit"
    >
      {{ checkout.loading ? 'Processing...' : 'Complete Checkout' }}
    </button>

    <slot name="submit" :loading="checkout.loading" :disabled="!checkout.session || checkout.status !== 'pending'" :on-submit="handleSubmit" />

    <div v-if="checkout.error" class="vkecom-checkout-error">
      {{ checkout.error.message }}
    </div>
  </form>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { useCheckout } from './useCheckout';
import type { ShippingAddress, BillingAddress, PaymentMethodDetails } from '@alejandrovrod/blocks-core';

interface Props {
  subtotal: number;
  cartId?: string;
  className?: string;
  onComplete?: (sessionId: string) => void;
  onError?: (error: Error) => void;
  renderFields?: (props: {
    shippingAddress: Partial<ShippingAddress>;
    billingAddress: Partial<BillingAddress>;
    paymentMethod: Partial<PaymentMethodDetails>;
    onShippingChange: (address: Partial<ShippingAddress>) => void;
    onBillingChange: (address: Partial<BillingAddress>) => void;
    onPaymentChange: (method: Partial<PaymentMethodDetails>) => void;
  }) => unknown;
  renderSubmit?: (props: { loading: boolean; disabled: boolean; onSubmit: () => void }) => unknown;
}

const props = defineProps<Props>();

const checkout = useCheckout();
const shippingAddress = ref<Partial<ShippingAddress>>({});
const billingAddress = ref<Partial<BillingAddress>>({});
const paymentMethod = ref<Partial<PaymentMethodDetails>>({});
const useSameAddress = ref(true);

// Initialize checkout session
watch(() => props.subtotal, () => {
  checkout.initialize(props.subtotal, props.cartId);
}, { immediate: true });

const handleSubmit = async () => {
  try {
    const shippingResult = checkout.setShippingAddress(shippingAddress.value as ShippingAddress);
    if (!shippingResult.valid) {
      props.onError?.(new Error(shippingResult.errors.map(e => e.message).join(', ')));
      return;
    }

    const billing = useSameAddress.value ? (shippingAddress.value as BillingAddress) : billingAddress.value;
    const billingResult = checkout.setBillingAddress(billing as BillingAddress);
    if (!billingResult.valid) {
      props.onError?.(new Error(billingResult.errors.map(e => e.message).join(', ')));
      return;
    }

    if (paymentMethod.value.method) {
      checkout.setPaymentMethod(paymentMethod.value as PaymentMethodDetails);
    }

    const validation = checkout.validate();
    if (!validation.valid) {
      props.onError?.(new Error(validation.errors.map(e => e.message).join(', ')));
      return;
    }

    await checkout.createPayment();
    props.onComplete?.(checkout.session.value?.id || '');
  } catch (error) {
    props.onError?.(error instanceof Error ? error : new Error(String(error)));
  }
};

const handleShippingChange = (address: Partial<ShippingAddress>) => {
  shippingAddress.value = address;
  if (useSameAddress.value) {
    billingAddress.value = address;
  }
};

const handleBillingChange = (address: Partial<BillingAddress>) => {
  billingAddress.value = address;
};

const handlePaymentChange = (method: Partial<PaymentMethodDetails>) => {
  paymentMethod.value = method;
};
</script>

// packages/blocks-react/src/checkout/CheckoutForm.tsx
/**
 * Checkout form component
 */

import React, { useState, FormEvent } from 'react';
import { useCheckout } from './useCheckout';
// Import types - using the same pattern as useCheckout.ts
// These types should be exported from @alejandrovrod/blocks-core but may need explicit exports
import type { 
  ShippingAddress,
  BillingAddress, 
  PaymentMethodDetails 
} from '@alejandrovrod/blocks-core';

export interface CheckoutFormProps {
  /**
   * Initial subtotal
   */
  subtotal: number;
  
  /**
   * Cart ID (optional)
   */
  cartId?: string;
  
  /**
   * Custom class name
   */
  className?: string;
  
  /**
   * On checkout complete callback
   */
  onComplete?: (sessionId: string) => void;
  
  /**
   * On error callback
   */
  onError?: (error: Error) => void;
  
  /**
   * Custom render for form fields
   */
  renderFields?: (props: {
    shippingAddress: Partial<ShippingAddress>;
    billingAddress: Partial<BillingAddress>;
    paymentMethod: Partial<PaymentMethodDetails>;
    onShippingChange: (address: Partial<ShippingAddress>) => void;
    onBillingChange: (address: Partial<BillingAddress>) => void;
    onPaymentChange: (method: Partial<PaymentMethodDetails>) => void;
  }) => React.ReactNode;
  
  /**
   * Custom render for submit button
   */
  renderSubmit?: (props: { loading: boolean; disabled: boolean; onSubmit: () => void }) => React.ReactNode;
  
  /**
   * Children (for custom content)
   */
  children?: React.ReactNode;
}

export function CheckoutForm({
  subtotal,
  cartId,
  className,
  onComplete,
  onError,
  renderFields,
  renderSubmit,
  children,
}: CheckoutFormProps) {
  const checkout = useCheckout();
  const [shippingAddress, setShippingAddress] = useState<Partial<ShippingAddress>>({});
  const [billingAddress, setBillingAddress] = useState<Partial<BillingAddress>>({});
  const [paymentMethod, setPaymentMethod] = useState<Partial<PaymentMethodDetails>>({});
  const [useSameAddress, setUseSameAddress] = useState(true);

  // Initialize checkout session
  React.useEffect(() => {
    checkout.initializeSession(subtotal, cartId);
  }, [subtotal, cartId, checkout]);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();

    try {
      // Set shipping address
      const shippingResult = checkout.setShippingAddress(shippingAddress as ShippingAddress);
      if (!shippingResult.valid) {
        onError?.(new Error(shippingResult.errors.map(e => e.message).join(', ')));
        return;
      }

      // Set billing address
      const billing = useSameAddress ? (shippingAddress as BillingAddress) : billingAddress;
      const billingResult = checkout.setBillingAddress(billing as BillingAddress);
      if (!billingResult.valid) {
        onError?.(new Error(billingResult.errors.map(e => e.message).join(', ')));
        return;
      }

      // Set payment method
      if (paymentMethod.method) {
        checkout.setPaymentMethod(paymentMethod as PaymentMethodDetails);
      }

      // Validate checkout
      const validation = checkout.validate();
      if (!validation.valid) {
        onError?.(new Error(validation.errors.map(e => e.message).join(', ')));
        return;
      }

      // Create payment
      await checkout.createPayment();
      onComplete?.(checkout.session?.id || '');
    } catch (error) {
      onError?.(error instanceof Error ? error : new Error(String(error)));
    }
  };

  const handleShippingChange = (address: Partial<ShippingAddress>) => {
    setShippingAddress(address);
    if (useSameAddress) {
      setBillingAddress(address);
    }
  };

  const handleBillingChange = (address: Partial<BillingAddress>) => {
    setBillingAddress(address);
  };

  const handlePaymentChange = (method: Partial<PaymentMethodDetails>) => {
    setPaymentMethod(method);
  };

  if (children) {
    return <div className={`vkecom-checkout-form ${className || ''}`}>{children}</div>;
  }

  return (
    <form className={`vkecom-checkout-form ${className || ''}`} onSubmit={handleSubmit}>
      {renderFields ? (
        renderFields({
          shippingAddress,
          billingAddress,
          paymentMethod,
          onShippingChange: handleShippingChange,
          onBillingChange: handleBillingChange,
          onPaymentChange: handlePaymentChange,
        })
      ) : (
        <>
          <div className="vkecom-checkout-shipping">
            <h3>Shipping Address</h3>
            <input
              type="text"
              placeholder="Street"
              value={shippingAddress.street || ''}
              onChange={(e) => handleShippingChange({ ...shippingAddress, street: e.target.value })}
              className="vkecom-checkout-field"
            />
            <input
              type="text"
              placeholder="City"
              value={shippingAddress.city || ''}
              onChange={(e) => handleShippingChange({ ...shippingAddress, city: e.target.value })}
              className="vkecom-checkout-field"
            />
            <input
              type="text"
              placeholder="Postal Code"
              value={shippingAddress.postalCode || ''}
              onChange={(e) => handleShippingChange({ ...shippingAddress, postalCode: e.target.value })}
              className="vkecom-checkout-field"
            />
            <input
              type="text"
              placeholder="Country"
              value={shippingAddress.country || ''}
              onChange={(e) => handleShippingChange({ ...shippingAddress, country: e.target.value })}
              className="vkecom-checkout-field"
            />
          </div>

          <label className="vkecom-checkout-same-address">
            <input
              type="checkbox"
              checked={useSameAddress}
              onChange={(e) => {
                setUseSameAddress(e.target.checked);
                if (e.target.checked) {
                  setBillingAddress(shippingAddress);
                }
              }}
            />
            Use same address for billing
          </label>

          {!useSameAddress && (
            <div className="vkecom-checkout-billing">
              <h3>Billing Address</h3>
              <input
                type="text"
                placeholder="Street"
                value={billingAddress.street || ''}
                onChange={(e) => handleBillingChange({ ...billingAddress, street: e.target.value })}
                className="vkecom-checkout-field"
              />
              <input
                type="text"
                placeholder="City"
                value={billingAddress.city || ''}
                onChange={(e) => handleBillingChange({ ...billingAddress, city: e.target.value })}
                className="vkecom-checkout-field"
              />
              <input
                type="text"
                placeholder="Postal Code"
                value={billingAddress.postalCode || ''}
                onChange={(e) => handleBillingChange({ ...billingAddress, postalCode: e.target.value })}
                className="vkecom-checkout-field"
              />
            </div>
          )}

          <div className="vkecom-checkout-payment">
            <h3>Payment Method</h3>
            <select
              value={paymentMethod.method || ''}
              onChange={(e) => handlePaymentChange({ ...paymentMethod, method: e.target.value as PaymentMethodDetails['method'] })}
              className="vkecom-checkout-field"
            >
              <option value="">Select payment method</option>
              <option value="credit_card">Credit Card</option>
              <option value="debit_card">Debit Card</option>
              <option value="mercado_pago">Mercado Pago</option>
            </select>
          </div>
        </>
      )}

      {renderSubmit ? (
        renderSubmit({
          loading: checkout.loading,
          disabled: !checkout.session || checkout.status !== 'pending',
          onSubmit: () => handleSubmit({ preventDefault: () => {} } as FormEvent),
        })
      ) : (
        <button
          type="submit"
          disabled={checkout.loading || !checkout.session || checkout.status !== 'pending'}
          className="vkecom-checkout-submit"
        >
          {checkout.loading ? 'Processing...' : 'Complete Checkout'}
        </button>
      )}

      {checkout.error && (
        <div className="vkecom-checkout-error">{checkout.error.message}</div>
      )}
    </form>
  );
}
