// packages/blocks-react/src/components/CartView.tsx
import React from 'react';
import { useCart } from '../hooks/useCart';
import { useCartSync } from '../hooks/useCartSync';
import { CartItem } from './CartItem';
import type { CartItemProps } from './CartItem';
import type { CartManagerOptions, CartItem as CartItemType, CartSyncOptions, CartHistoryOptions } from '@vk/blocks-core';

export interface CartViewProps {
  className?: string;
  emptyMessage?: React.ReactNode;
  renderEmpty?: () => React.ReactNode;
  renderItem?: (item: CartItemType) => React.ReactNode;
  renderHeader?: () => React.ReactNode;
  renderFooter?: () => React.ReactNode;
  cartOptions?: CartManagerOptions;
  itemProps?: Omit<CartItemProps, 'item'>;
  enableSync?: boolean;
  syncOptions?: CartSyncOptions;
  enableHistory?: boolean;
  historyOptions?: CartHistoryOptions;
}

/**
 * CartView component - Displays the full cart with all items
 * Fully customizable, no styles included
 * Uses logical CSS classes: vkecom-cart-view, vkecom-cart-list, etc.
 */
export function CartView({
  className = '',
  emptyMessage = 'Your cart is empty',
  renderEmpty,
  renderItem,
  renderHeader,
  renderFooter,
  cartOptions,
  itemProps,
  enableSync = false,
  syncOptions,
  enableHistory = false,
  historyOptions,
}: CartViewProps) {
  const { items, removeItem, updateQuantity } = useCart(cartOptions);
  
  // Enable cart synchronization if requested
  useCartSync(enableSync ? syncOptions : undefined);

  const handleIncrease = (itemId: string) => {
    const item = items.find((i) => i.id === itemId);
    if (item) {
      updateQuantity(itemId, item.quantity + 1);
    }
  };

  const handleDecrease = (itemId: string) => {
    const item = items.find((i) => i.id === itemId);
    if (item) {
      if (item.quantity > 1) {
        updateQuantity(itemId, item.quantity - 1);
      } else {
        removeItem(itemId);
      }
    }
  };

  return (
    <div className={`vkecom-cart-view ${className}`}>
      {renderHeader && (
        <div className="vkecom-cart-header">{renderHeader()}</div>
      )}

      {items.length === 0 ? (
        <div className="vkecom-cart-empty">
          {renderEmpty ? renderEmpty() : <p>{emptyMessage}</p>}
        </div>
      ) : (
        <>
          <div className="vkecom-cart-list" role="list">
            {items.map((item) => (
              <div key={item.id} role="listitem">
                {renderItem ? (
                  renderItem(item)
                ) : (
                  <CartItem
                    item={item}
                    onIncrease={handleIncrease}
                    onDecrease={handleDecrease}
                    onRemove={removeItem}
                    {...itemProps}
                  />
                )}
              </div>
            ))}
          </div>

          {renderFooter && (
            <div className="vkecom-cart-footer">{renderFooter()}</div>
          )}
        </>
      )}
    </div>
  );
}

// packages/blocks-angular/src/components/cart-view.component.ts
import { Component, Input, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CartService } from '../services/cart.service';
import { CartSyncService } from '../services/cart-sync.service';
import { CartItemComponent } from './cart-item.component';
import type { CartSyncOptions } from '@vk/blocks-core';

/**
 * CartView component - Displays the full cart with all items
 * Fully customizable via CSS classes
 */
@Component({
  selector: 'vk-cart-view',
  standalone: true,
  imports: [CommonModule, CartItemComponent],
  templateUrl: './cart-view.component.html',
})
export class CartViewComponent implements OnInit, OnDestroy {
  @Input() className?: string;
  @Input() emptyMessage = 'Your cart is empty';
  @Input() showHeader = true;
  @Input() enableSync = false;
  @Input() syncOptions?: CartSyncOptions;
  @Input() enableHistory = false;
  @Input() historyOptions?: CartHistoryOptions;

  // Use signals from the service
  items;

  constructor(
    public cartService: CartService,
    private cartSyncService: CartSyncService
  ) {
    this.items = this.cartService.items;
  }

  ngOnInit(): void {
    if (this.enableSync) {
      this.cartSyncService.initialize(this.syncOptions);
    }
  }

  ngOnDestroy(): void {
    if (this.enableSync) {
      this.cartSyncService.stop();
    }
  }

  handleIncrease(itemId: string): void {
    const item = this.items().find((i) => i.id === itemId);
    if (item) {
      this.cartService.updateQuantity(itemId, item.quantity + 1);
    }
  }

  handleDecrease(itemId: string): void {
    const item = this.items().find((i) => i.id === itemId);
    if (item) {
      if (item.quantity > 1) {
        this.cartService.updateQuantity(itemId, item.quantity - 1);
      } else {
        this.cartService.removeItem(itemId);
      }
    }
  }

  handleRemove(itemId: string): void {
    this.cartService.removeItem(itemId);
  }
}


<div [class]="'vkecom-cart-view ' + (className || '')">
  <div *ngIf="showHeader" class="vkecom-cart-header">
    <h2 class="vkecom-cart-title">Cart</h2>
  </div>

  <div *ngIf="items().length === 0" class="vkecom-cart-empty">
    <p>{{ emptyMessage }}</p>
  </div>

  <div *ngIf="items().length > 0" class="vkecom-cart-list" role="list">
    <div *ngFor="let item of items()" role="listitem">
      <vk-cart-item
        [item]="item"
        (increase)="handleIncrease($event)"
        (decrease)="handleDecrease($event)"
        (remove)="handleRemove($event)"
      />
    </div>
  </div>
</div>
