// packages/blocks-react/src/components/CartSummary.tsx
import React from 'react';
import { useCart } from '../hooks/useCart';
import type { CartManagerOptions } from '@vk/blocks-core';

export interface CartSummaryProps {
  className?: string;
  cartOptions?: CartManagerOptions;
  showItemCount?: boolean;
  showSubtotal?: boolean;
  showTax?: boolean;
  taxRate?: number;
  showShipping?: boolean;
  shippingCost?: number;
  showTotal?: boolean;
  renderSubtotal?: (subtotal: number) => React.ReactNode;
  renderTax?: (tax: number) => React.ReactNode;
  renderShipping?: (shipping: number) => React.ReactNode;
  renderTotal?: (total: number) => React.ReactNode;
  renderItemCount?: (count: number) => React.ReactNode;
  renderCheckout?: (onCheckout: () => void) => React.ReactNode;
  onCheckout?: () => void;
  formatPrice?: (price: number) => string;
}

/**
 * CartSummary component - Displays cart summary with totals
 * Fully customizable, no styles included
 * Uses logical CSS classes: vkecom-cart-summary, vkecom-cart-summary-total, etc.
 */
export function CartSummary({
  className = '',
  cartOptions,
  showItemCount = true,
  showSubtotal = true,
  showTax = false,
  taxRate = 0,
  showShipping = false,
  shippingCost = 0,
  showTotal = true,
  renderSubtotal,
  renderTax,
  renderShipping,
  renderTotal,
  renderItemCount,
  renderCheckout,
  onCheckout,
  formatPrice = (price) => `$${price.toFixed(2)}`,
}: CartSummaryProps) {
  const { total, itemCount } = useCart(cartOptions);

  const subtotal = total;
  const tax = subtotal * taxRate;
  const shipping = showShipping ? shippingCost : 0;
  const finalTotal = subtotal + tax + shipping;

  const handleCheckout = () => {
    if (onCheckout) {
      onCheckout();
    }
  };

  return (
    <div className={`vkecom-cart-summary ${className}`}>
      {showItemCount && (
        <div className="vkecom-cart-summary-item-count">
          {renderItemCount ? (
            renderItemCount(itemCount)
          ) : (
            <span>
              {itemCount} {itemCount === 1 ? 'item' : 'items'}
            </span>
          )}
        </div>
      )}

      {showSubtotal && (
        <div className="vkecom-cart-summary-subtotal">
          {renderSubtotal ? (
            renderSubtotal(subtotal)
          ) : (
            <>
              <span className="vkecom-cart-summary-label">Subtotal:</span>
              <span className="vkecom-cart-summary-value">{formatPrice(subtotal)}</span>
            </>
          )}
        </div>
      )}

      {showTax && taxRate > 0 && (
        <div className="vkecom-cart-summary-tax">
          {renderTax ? (
            renderTax(tax)
          ) : (
            <>
              <span className="vkecom-cart-summary-label">Tax:</span>
              <span className="vkecom-cart-summary-value">{formatPrice(tax)}</span>
            </>
          )}
        </div>
      )}

      {showShipping && (
        <div className="vkecom-cart-summary-shipping">
          {renderShipping ? (
            renderShipping(shipping)
          ) : (
            <>
              <span className="vkecom-cart-summary-label">Shipping:</span>
              <span className="vkecom-cart-summary-value">{formatPrice(shipping)}</span>
            </>
          )}
        </div>
      )}

      {showTotal && (
        <div className="vkecom-cart-summary-total">
          {renderTotal ? (
            renderTotal(finalTotal)
          ) : (
            <>
              <span className="vkecom-cart-summary-label">Total:</span>
              <span className="vkecom-cart-summary-value">{formatPrice(finalTotal)}</span>
            </>
          )}
        </div>
      )}

      {renderCheckout && (
        <div className="vkecom-cart-summary-checkout">
          {renderCheckout(handleCheckout)}
        </div>
      )}
    </div>
  );
}

// packages/blocks-angular/src/components/cart-summary.component.ts
import { Component, Input, Output, EventEmitter, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CartService } from '../services/cart.service';

/**
 * CartSummary component - Displays cart summary with totals
 * Fully customizable via CSS classes
 */
@Component({
  selector: 'vk-cart-summary',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './cart-summary.component.html',
})
export class CartSummaryComponent {
  @Input() className?: string;
  @Input() showItemCount = true;
  @Input() showSubtotal = true;
  @Input() showTax = false;
  @Input() taxRate = 0;
  @Input() showShipping = false;
  @Input() shippingCost = 0;
  @Input() showTotal = true;
  @Input() showCheckoutButton = false;
  @Output() checkout = new EventEmitter<void>();

  // Use signals from the service
  total;
  itemCount;

  subtotal;
  tax;
  shipping;
  finalTotal;

  constructor(public cartService: CartService) {
    this.total = this.cartService.total;
    this.itemCount = this.cartService.itemCount;
    this.subtotal = computed(() => this.total());
    this.tax = computed(() => this.subtotal() * this.taxRate);
    this.shipping = computed(() => (this.showShipping ? this.shippingCost : 0));
    this.finalTotal = computed(() => this.subtotal() + this.tax() + this.shipping());
  }

  handleCheckout(): void {
    this.checkout.emit();
  }

  formatPrice(price: number): string {
    return `$${price.toFixed(2)}`;
  }
}



<div [class]="'vkecom-cart-summary ' + (className || '')">
  <div *ngIf="showItemCount" class="vkecom-cart-summary-item-count">
    <span>
      {{ itemCount() }} {{ itemCount() === 1 ? 'item' : 'items' }}
    </span>
  </div>

  <div *ngIf="showSubtotal" class="vkecom-cart-summary-subtotal">
    <span class="vkecom-cart-summary-label">Subtotal:</span>
    <span class="vkecom-cart-summary-value">{{ formatPrice(subtotal()) }}</span>
  </div>

  <div *ngIf="showTax && taxRate > 0" class="vkecom-cart-summary-tax">
    <span class="vkecom-cart-summary-label">Tax:</span>
    <span class="vkecom-cart-summary-value">{{ formatPrice(tax()) }}</span>
  </div>

  <div *ngIf="showShipping" class="vkecom-cart-summary-shipping">
    <span class="vkecom-cart-summary-label">Shipping:</span>
    <span class="vkecom-cart-summary-value">{{ formatPrice(shipping()) }}</span>
  </div>

  <div *ngIf="showTotal" class="vkecom-cart-summary-total">
    <span class="vkecom-cart-summary-label">Total:</span>
    <span class="vkecom-cart-summary-value">{{ formatPrice(finalTotal()) }}</span>
  </div>

  <div *ngIf="showCheckoutButton" class="vkecom-cart-summary-checkout">
    <button
      type="button"
      class="vkecom-cart-summary-checkout-button"
      (click)="handleCheckout()"
    >
      Checkout
    </button>
  </div>
</div>
