// packages/blocks-vue/src/products/ProductSearch.vue
<template>
  <form :class="['vkecom-product-search', className]" @submit.prevent="handleSubmit">
    <slot name="input" :value="localQuery" :on-change="handleChange" :on-submit="handleSubmit">
      <input
        v-model="localQuery"
        type="search"
        :placeholder="placeholder"
        class="vkecom-product-search-input"
      />
    </slot>
  </form>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useProductSearch } from './useProductSearch';
import type { SearchOptions } from '@vk/blocks-core';

interface Props {
  initialQuery?: string;
  initialOptions?: SearchOptions;
  onSearch?: (query: string, options: SearchOptions) => void;
  className?: string;
  placeholder?: string;
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: 'Search products...',
});

const search = useProductSearch(props.initialOptions);
const localQuery = ref(props.initialQuery || search.query.value);

const handleSubmit = () => {
  search.setQuery(localQuery.value);
  props.onSearch?.(localQuery.value, { ...search.options.value, query: localQuery.value });
};

const handleChange = (e: Event) => {
  const target = e.target as HTMLInputElement;
  localQuery.value = target.value;
};
</script>

// packages/blocks-angular/src/products/product-search.component.ts
/**
 * Product search component
 */

import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ProductSearchService } from './product-search.service';
import type { SearchOptions } from '@vk/blocks-core';

@Component({
  selector: 'vk-product-search',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <form
      [class]="'vkecom-product-search ' + (className || '')"
      (ngSubmit)="handleSubmit()"
    >
      <input
        type="search"
        [(ngModel)]="localQuery"
        [placeholder]="placeholder"
        name="searchQuery"
        class="vkecom-product-search-input"
      />
    </form>
  `,
})
export class ProductSearchComponent {
  @Input() initialQuery?: string;
  @Input() initialOptions?: SearchOptions;
  @Output() search = new EventEmitter<{ query: string; options: SearchOptions }>();
  @Input() className?: string;
  @Input() placeholder = 'Search products...';

  localQuery = '';

  constructor(private searchService: ProductSearchService) {
    if (this.initialQuery) {
      this.localQuery = this.initialQuery;
      this.searchService.setQuery(this.initialQuery);
    }
    if (this.initialOptions) {
      this.searchService.setOptions(this.initialOptions);
    }
  }

  handleSubmit(): void {
    this.searchService.setQuery(this.localQuery);
    this.search.emit({
      query: this.localQuery,
      options: this.searchService.options(),
    });
  }
}


<form
  [class]="'vkecom-product-search ' + (className || '')"
  (ngSubmit)="handleSubmit()"
>
  <input
    type="search"
    [(ngModel)]="localQuery"
    [placeholder]="placeholder"
    name="searchQuery"
    class="vkecom-product-search-input"
  />
</form>
