// packages/blocks-vue/src/components/ProductCard.vue
<template>
  <article
    v-if="!$slots.default"
    :class="['vkecom-product-card', className]"
    itemscope
    itemtype="https://schema.org/Product"
  >
    <slot name="image" :product="product">
      <div class="vkecom-product-image">
        <img
          v-if="product.image"
          :src="product.image"
          :alt="product.name"
          loading="lazy"
          itemprop="image"
        />
        <div
          v-else
          class="vkecom-product-image-placeholder"
          aria-hidden="true"
        >
          No image
        </div>
      </div>
    </slot>

    <div class="vkecom-product-content">
      <slot name="title" :product="product">
        <h3 class="vkecom-product-title" itemprop="name">
          {{ product.name }}
        </h3>
      </slot>

      <p
        v-if="product.description"
        class="vkecom-product-description"
        itemprop="description"
      >
        {{ product.description }}
      </p>

      <slot name="price" :product="product">
        <div
          class="vkecom-product-price"
          itemprop="offers"
          itemscope
          itemtype="https://schema.org/Offer"
        >
          <span
            class="vkecom-product-price-value"
            itemprop="price"
            :content="product.price.toString()"
          >
            ${{ product.price.toFixed(2) }}
          </span>
          <meta itemprop="priceCurrency" content="USD" />
        </div>
      </slot>

      <slot name="button" :product="product" :onAddToCart="handleAddToCart">
        <button
          type="button"
          class="vkecom-product-button"
          @click="handleAddToCart"
          :aria-label="`Add ${product.name} to cart`"
        >
          Add to Cart
        </button>
      </slot>
    </div>
  </article>

  <div v-else :class="['vkecom-product-card', className]">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { useCart } from '../composables/useCart';
import type { Product } from '@alejandrovrod/blocks-core';

export interface ProductCardProps {
  product: Product;
  className?: string;
  quantity?: number;
}

const props = withDefaults(defineProps<ProductCardProps>(), {
  className: '',
  quantity: 1,
});

const emit = defineEmits<{
  addToCart: [product: Product];
}>();

const { addItem } = useCart();

const handleAddToCart = () => {
  addItem(props.product, props.quantity);
  emit('addToCart', props.product);
};
</script>

// packages/blocks-angular/src/products/product-card.component.ts
import { Component, Input, Output, EventEmitter, ContentChildren, QueryList, ElementRef, AfterContentInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CartService } from '../services/cart.service';
import type { Product } from '@alejandrovrod/blocks-core';

/**
 * ProductCard component - Displays a product card with add to cart functionality
 * Fully customizable via CSS classes
 * 
 * Usage examples:
 * 
 * Basic usage:
 * <vk-product-card [product]="product"></vk-product-card>
 * 
 * Custom slots (use attributes to target specific slots):
 * <vk-product-card [product]="product">
 *   <div image>Custom image content</div>
 *   <h2 title>Custom title</h2>
 *   <span price>Custom price</span>
 *   <button button (click)="handleAdd()">Custom button</button>
 * </vk-product-card>
 * 
 * Fully custom content:
 * <vk-product-card [product]="product" [useCustomContent]="true">
 *   <div>Your completely custom content</div>
 * </vk-product-card>
 */
@Component({
  selector: 'vk-product-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './product-card.component.html',
})
export class ProductCardComponent implements AfterContentInit {
  @Input() product!: Product;
  @Input() className?: string;
  @Input() quantity: number = 1;
  @Input() useCustomContent: boolean = false;
  @Output() addToCart = new EventEmitter<Product>();

  @ContentChildren('[image]', { read: ElementRef }) imageSlots!: QueryList<ElementRef>;
  @ContentChildren('[title]', { read: ElementRef }) titleSlots!: QueryList<ElementRef>;
  @ContentChildren('[price]', { read: ElementRef }) priceSlots!: QueryList<ElementRef>;
  @ContentChildren('[button]', { read: ElementRef }) buttonSlots!: QueryList<ElementRef>;

  hasImageSlot = false;
  hasTitleSlot = false;
  hasPriceSlot = false;
  hasButtonSlot = false;

  constructor(private cartService: CartService) {}

  ngAfterContentInit(): void {
    this.hasImageSlot = this.imageSlots.length > 0;
    this.hasTitleSlot = this.titleSlots.length > 0;
    this.hasPriceSlot = this.priceSlots.length > 0;
    this.hasButtonSlot = this.buttonSlots.length > 0;
  }

  onAddToCart(): void {
    this.cartService.addItem(this.product, this.quantity);
    this.addToCart.emit(this.product);
  }

  formatPrice(price: number): string {
    return `$${price.toFixed(2)}`;
  }
}



<article
  *ngIf="!useCustomContent"
  [class]="'vkecom-product-card ' + (className || '')"
  itemscope
  itemtype="https://schema.org/Product"
>
  <!-- Image slot -->
  <ng-content select="[image]"></ng-content>
  <div *ngIf="!hasImageSlot" class="vkecom-product-image">
    <img
      *ngIf="product.image"
      [src]="product.image"
      [alt]="product.name"
      loading="lazy"
      itemprop="image"
    />
    <div
      *ngIf="!product.image"
      class="vkecom-product-image-placeholder"
      aria-hidden="true"
    >
      No image
    </div>
  </div>

  <div class="vkecom-product-content">
    <!-- Title slot -->
    <ng-content select="[title]"></ng-content>
    <h3 *ngIf="!hasTitleSlot" class="vkecom-product-title" itemprop="name">
      {{ product.name }}
    </h3>

    <p
      *ngIf="product.description"
      class="vkecom-product-description"
      itemprop="description"
    >
      {{ product.description }}
    </p>

    <!-- Price slot -->
    <ng-content select="[price]"></ng-content>
    <div
      *ngIf="!hasPriceSlot"
      class="vkecom-product-price"
      itemprop="offers"
      itemscope
      itemtype="https://schema.org/Offer"
    >
      <span
        class="vkecom-product-price-value"
        itemprop="price"
        [attr.content]="product.price.toString()"
      >
        {{ '$' + formatPrice(product.price) }}
      </span>
      <meta itemprop="priceCurrency" content="USD" />
    </div>

    <!-- Button slot -->
    <ng-content select="[button]"></ng-content>
    <button
      *ngIf="!hasButtonSlot"
      type="button"
      class="vkecom-product-button"
      (click)="onAddToCart()"
      [attr.aria-label]="'Add ' + product.name + ' to cart'"
    >
      Add to Cart
    </button>
  </div>
</article>

<div *ngIf="useCustomContent" [class]="'vkecom-product-card ' + (className || '')">
  <ng-content></ng-content>
</div>
