// packages/blocks-angular/src/shipping/shipping-calculator.component.ts
/**
 * Shipping calculator component
 */

import { Component, Input, Output, EventEmitter, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ShippingService } from './shipping.service';
import type { ShippingAddress, ShippingCalculationRequest } from '@vk/blocks-core';

@Component({
  selector: 'vk-shipping-calculator',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div [class]="'vkecom-shipping-calculator ' + (className || '')">
      <form (ngSubmit)="handleSubmit()">
        <div class="vkecom-shipping-address-form">
          <input
            type="text"
            placeholder="Street"
            [(ngModel)]="address.street"
            name="street"
            class="vkecom-shipping-field"
          />
          <input
            type="text"
            placeholder="City"
            [(ngModel)]="address.city"
            name="city"
            class="vkecom-shipping-field"
          />
          <input
            type="text"
            placeholder="Postal Code"
            [(ngModel)]="address.postalCode"
            name="postalCode"
            class="vkecom-shipping-field"
          />
          <input
            type="text"
            placeholder="Country"
            [(ngModel)]="address.country"
            name="country"
            class="vkecom-shipping-field"
          />
          <button
            type="submit"
            [disabled]="shipping.loading()"
            class="vkecom-shipping-calculate-button"
          >
            {{ shipping.loading() ? 'Calculating...' : 'Calculate Shipping' }}
          </button>
        </div>

        <div *ngIf="shipping.error()" class="vkecom-shipping-error">
          {{ shipping.error()?.message }}
        </div>
      </form>

      <div *ngIf="shipping.rates().length > 0" class="vkecom-shipping-rates">
        <h3>Shipping Options</h3>
        <div
          *ngFor="let rate of shipping.rates()"
          class="vkecom-shipping-rate"
        >
          <div class="vkecom-shipping-rate-name">{{ rate.option.name }}</div>
          <div class="vkecom-shipping-rate-cost">
            ${{ rate.cost.toFixed(2) }} {{ rate.currency }}
          </div>
          <div *ngIf="rate.estimatedDays" class="vkecom-shipping-rate-days">
            {{ rate.estimatedDays.min }}-{{ rate.estimatedDays.max }} days
          </div>
        </div>
      </div>
    </div>
  `,
})
export class ShippingCalculatorComponent {
  @Input() items!: Array<{
    weight?: number;
    dimensions?: {
      length?: number;
      width?: number;
      height?: number;
    };
    quantity: number;
    value?: number;
  }>;
  @Input() className?: string;
  @Output() ratesCalculated = new EventEmitter<import('@vk/blocks-core').ShippingRate[]>();

  address = signal<Partial<ShippingAddress>>({});

  constructor(public shipping: ShippingService) {}

  async handleSubmit(): Promise<void> {
    if (
      !this.address().street ||
      !this.address().city ||
      !this.address().postalCode ||
      !this.address().country
    ) {
      return;
    }

    try {
      const request: ShippingCalculationRequest = {
        address: this.address() as ShippingAddress,
        items: this.items,
      };

      const result = await this.shipping.calculateRates(request);
      this.ratesCalculated.emit(result.rates);
    } catch (error) {
      // Error handled by service
    }
  }
}


<div [class]="'vkecom-shipping-calculator ' + (className || '')">
  <form (ngSubmit)="handleSubmit()">
    <div class="vkecom-shipping-address-form">
      <input
        type="text"
        placeholder="Street"
        [(ngModel)]="address.street"
        name="street"
        class="vkecom-shipping-field"
      />
      <input
        type="text"
        placeholder="City"
        [(ngModel)]="address.city"
        name="city"
        class="vkecom-shipping-field"
      />
      <input
        type="text"
        placeholder="Postal Code"
        [(ngModel)]="address.postalCode"
        name="postalCode"
        class="vkecom-shipping-field"
      />
      <input
        type="text"
        placeholder="Country"
        [(ngModel)]="address.country"
        name="country"
        class="vkecom-shipping-field"
      />
      <button
        type="submit"
        [disabled]="shipping.loading()"
        class="vkecom-shipping-calculate-button"
      >
        {{ shipping.loading() ? 'Calculating...' : 'Calculate Shipping' }}
      </button>
    </div>

    <div *ngIf="shipping.error()" class="vkecom-shipping-error">
      {{ shipping.error()?.message }}
    </div>
  </form>

  <div *ngIf="shipping.rates().length > 0" class="vkecom-shipping-rates">
    <h3>Shipping Options</h3>
    <div
      *ngFor="let rate of shipping.rates()"
      class="vkecom-shipping-rate"
    >
      <div class="vkecom-shipping-rate-name">{{ rate.option.name }}</div>
      <div class="vkecom-shipping-rate-cost">
        {{ formatPrice(rate.cost) }} {{ rate.currency }}
      </div>
      <div *ngIf="rate.estimatedDays" class="vkecom-shipping-rate-days">
        {{ rate.estimatedDays.min }}-{{ rate.estimatedDays.max }} days
      </div>
    </div>
  </div>
</div>

// packages/blocks-vue/src/shipping/ShippingCalculator.vue
<template>
  <div :class="['vkecom-shipping-calculator', className]">
    <form @submit.prevent="handleSubmit">
      <slot
        name="address-form"
        :address="address"
        :on-change="handleAddressChange"
        :on-submit="handleSubmit"
      >
        <div class="vkecom-shipping-address-form">
          <input
            v-model="address.street"
            type="text"
            placeholder="Street"
            class="vkecom-shipping-field"
          />
          <input
            v-model="address.city"
            type="text"
            placeholder="City"
            class="vkecom-shipping-field"
          />
          <input
            v-model="address.postalCode"
            type="text"
            placeholder="Postal Code"
            class="vkecom-shipping-field"
          />
          <input
            v-model="address.country"
            type="text"
            placeholder="Country"
            class="vkecom-shipping-field"
          />
          <button type="submit" :disabled="shipping.loading" class="vkecom-shipping-calculate-button">
            {{ shipping.loading ? 'Calculating...' : 'Calculate Shipping' }}
          </button>
        </div>
      </slot>

      <div v-if="shipping.error" class="vkecom-shipping-error">
        {{ shipping.error.message }}
      </div>
    </form>

    <slot name="rates" :rates="shipping.rates" :loading="shipping.loading" :on-select="() => {}">
      <div v-if="shipping.rates.length > 0" class="vkecom-shipping-rates">
        <h3>Shipping Options</h3>
        <div
          v-for="rate in shipping.rates"
          :key="rate.option.id"
          class="vkecom-shipping-rate"
        >
          <div class="vkecom-shipping-rate-name">{{ rate.option.name }}</div>
          <div class="vkecom-shipping-rate-cost">
            ${{ rate.cost.toFixed(2) }} {{ rate.currency }}
          </div>
          <div v-if="rate.estimatedDays" class="vkecom-shipping-rate-days">
            {{ rate.estimatedDays.min }}-{{ rate.estimatedDays.max }} days
          </div>
        </div>
      </div>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useShipping } from './useShipping';
import type { ShippingAddress, ShippingCalculationRequest } from '@vk/blocks-core';

interface Props {
  items: Array<{
    weight?: number;
    dimensions?: {
      length?: number;
      width?: number;
      height?: number;
    };
    quantity: number;
    value?: number;
  }>;
  className?: string;
  onRatesCalculated?: (rates: import('@vk/blocks-core').ShippingRate[]) => void;
}

const props = defineProps<Props>();

const shipping = useShipping();
const address = ref<Partial<ShippingAddress>>({});

const handleSubmit = async () => {
  if (!address.value.street || !address.value.city || !address.value.postalCode || !address.value.country) {
    return;
  }

  try {
    const request: ShippingCalculationRequest = {
      address: address.value as ShippingAddress,
      items: props.items,
    };

    const result = await shipping.calculate(request);
    props.onRatesCalculated?.(result.rates);
  } catch (error) {
    // Error handled by hook
  }
};

const handleAddressChange = (newAddress: Partial<ShippingAddress>) => {
  address.value = newAddress;
};
</script>
