// packages/blocks-react/src/shipping/ShippingCalculator.tsx
/**
 * Shipping calculator component
 */

import React, { useState, FormEvent } from 'react';
import { useShipping } from './useShipping';
import type { ShippingAddress, ShippingCalculationRequest } from '@alejandrovrod/blocks-core';

export interface ShippingCalculatorProps {
  /**
   * Items to calculate shipping for
   */
  items: Array<{
    weight?: number;
    dimensions?: {
      length?: number;
      width?: number;
      height?: number;
    };
    quantity: number;
    value?: number;
  }>;
  
  /**
   * Custom class name
   */
  className?: string;
  
  /**
   * On rates calculated callback
   */
  onRatesCalculated?: (rates: import('@alejandrovrod/blocks-core').ShippingRate[]) => void;
  
  /**
   * Custom render for address form
   */
  renderAddressForm?: (props: {
    address: Partial<ShippingAddress>;
    onChange: (address: Partial<ShippingAddress>) => void;
    onSubmit: () => void;
  }) => React.ReactNode;
  
  /**
   * Custom render for rates
   */
  renderRates?: (props: {
    rates: import('@alejandrovrod/blocks-core').ShippingRate[];
    loading: boolean;
    onSelect: (rate: import('@alejandrovrod/blocks-core').ShippingRate) => void;
  }) => React.ReactNode;
  
  /**
   * Children (for custom content)
   */
  children?: React.ReactNode;
}

export function ShippingCalculator({
  items,
  className,
  onRatesCalculated,
  renderAddressForm,
  renderRates,
  children,
}: ShippingCalculatorProps) {
  const shipping = useShipping();
  const [address, setAddress] = useState<Partial<ShippingAddress>>({});

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();

    if (!address.street || !address.city || !address.postalCode || !address.country) {
      return;
    }

    try {
      const request: ShippingCalculationRequest = {
        address: address as ShippingAddress,
        items,
      };

      const result = await shipping.calculate(request);
      onRatesCalculated?.(result.rates);
    } catch (error) {
      // Error handled by hook
    }
  };

  const handleAddressChange = (newAddress: Partial<ShippingAddress>) => {
    setAddress(newAddress);
  };

  if (children) {
    return <div className={`vkecom-shipping-calculator ${className || ''}`}>{children}</div>;
  }

  return (
    <div className={`vkecom-shipping-calculator ${className || ''}`}>
      <form onSubmit={handleSubmit}>
        {renderAddressForm ? (
          renderAddressForm({
            address,
            onChange: handleAddressChange,
            onSubmit: () => handleSubmit({ preventDefault: () => {} } as FormEvent),
          })
        ) : (
          <div className="vkecom-shipping-address-form">
            <input
              type="text"
              placeholder="Street"
              value={address.street || ''}
              onChange={(e) => handleAddressChange({ ...address, street: e.target.value })}
              className="vkecom-shipping-field"
            />
            <input
              type="text"
              placeholder="City"
              value={address.city || ''}
              onChange={(e) => handleAddressChange({ ...address, city: e.target.value })}
              className="vkecom-shipping-field"
            />
            <input
              type="text"
              placeholder="Postal Code"
              value={address.postalCode || ''}
              onChange={(e) => handleAddressChange({ ...address, postalCode: e.target.value })}
              className="vkecom-shipping-field"
            />
            <input
              type="text"
              placeholder="Country"
              value={address.country || ''}
              onChange={(e) => handleAddressChange({ ...address, country: e.target.value })}
              className="vkecom-shipping-field"
            />
            <button type="submit" disabled={shipping.loading} className="vkecom-shipping-calculate-button">
              {shipping.loading ? 'Calculating...' : 'Calculate Shipping'}
            </button>
          </div>
        )}

        {shipping.error && (
          <div className="vkecom-shipping-error">{shipping.error.message}</div>
        )}
      </form>

      {renderRates ? (
        renderRates({
          rates: shipping.rates,
          loading: shipping.loading,
          onSelect: () => {},
        })
      ) : (
        shipping.rates.length > 0 && (
          <div className="vkecom-shipping-rates">
            <h3>Shipping Options</h3>
            {shipping.rates.map((rate) => (
              <div key={rate.option.id} className="vkecom-shipping-rate">
                <div className="vkecom-shipping-rate-name">{rate.option.name}</div>
                <div className="vkecom-shipping-rate-cost">
                  ${rate.cost.toFixed(2)} {rate.currency}
                </div>
                {rate.estimatedDays && (
                  <div className="vkecom-shipping-rate-days">
                    {rate.estimatedDays.min}-{rate.estimatedDays.max} days
                  </div>
                )}
              </div>
            ))}
          </div>
        )
      )}
    </div>
  );
}

// packages/blocks-vue/src/shipping/ShippingCalculator.vue
<template>
  <div :class="['vkecom-shipping-calculator', className]">
    <form @submit.prevent="handleSubmit">
      <slot
        name="address-form"
        :address="address"
        :on-change="handleAddressChange"
        :on-submit="handleSubmit"
      >
        <div class="vkecom-shipping-address-form">
          <input
            v-model="address.street"
            type="text"
            placeholder="Street"
            class="vkecom-shipping-field"
          />
          <input
            v-model="address.city"
            type="text"
            placeholder="City"
            class="vkecom-shipping-field"
          />
          <input
            v-model="address.postalCode"
            type="text"
            placeholder="Postal Code"
            class="vkecom-shipping-field"
          />
          <input
            v-model="address.country"
            type="text"
            placeholder="Country"
            class="vkecom-shipping-field"
          />
          <button type="submit" :disabled="shipping.loading" class="vkecom-shipping-calculate-button">
            {{ shipping.loading ? 'Calculating...' : 'Calculate Shipping' }}
          </button>
        </div>
      </slot>

      <div v-if="shipping.error" class="vkecom-shipping-error">
        {{ shipping.error.message }}
      </div>
    </form>

    <slot name="rates" :rates="shipping.rates" :loading="shipping.loading" :on-select="() => {}">
      <div v-if="shipping.rates.length > 0" class="vkecom-shipping-rates">
        <h3>Shipping Options</h3>
        <div
          v-for="rate in shipping.rates"
          :key="rate.option.id"
          class="vkecom-shipping-rate"
        >
          <div class="vkecom-shipping-rate-name">{{ rate.option.name }}</div>
          <div class="vkecom-shipping-rate-cost">
            ${{ rate.cost.toFixed(2) }} {{ rate.currency }}
          </div>
          <div v-if="rate.estimatedDays" class="vkecom-shipping-rate-days">
            {{ rate.estimatedDays.min }}-{{ rate.estimatedDays.max }} days
          </div>
        </div>
      </div>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useShipping } from './useShipping';
import type { ShippingAddress, ShippingCalculationRequest } from '@alejandrovrod/blocks-core';

interface Props {
  items: Array<{
    weight?: number;
    dimensions?: {
      length?: number;
      width?: number;
      height?: number;
    };
    quantity: number;
    value?: number;
  }>;
  className?: string;
  onRatesCalculated?: (rates: import('@alejandrovrod/blocks-core').ShippingRate[]) => void;
}

const props = defineProps<Props>();

const shipping = useShipping();
const address = ref<Partial<ShippingAddress>>({});

const handleSubmit = async () => {
  if (!address.value.street || !address.value.city || !address.value.postalCode || !address.value.country) {
    return;
  }

  try {
    const request: ShippingCalculationRequest = {
      address: address.value as ShippingAddress,
      items: props.items,
    };

    const result = await shipping.calculate(request);
    props.onRatesCalculated?.(result.rates);
  } catch (error) {
    // Error handled by hook
  }
};

const handleAddressChange = (newAddress: Partial<ShippingAddress>) => {
  address.value = newAddress;
};
</script>
