// packages/blocks-vue/src/products/ProductFilters.vue
<template>
  <div :class="['vkecom-product-filters', className]">
    <slot name="filters" :filters="filters" :facets="facets" :on-change="onChange">
      <div class="vkecom-product-filters-section">
        <h3>Price Range</h3>
        <input
          type="number"
          placeholder="Min"
          :value="filters.priceRange?.min || ''"
          @input="handlePriceMinChange"
          class="vkecom-product-filters-input"
        />
        <input
          type="number"
          placeholder="Max"
          :value="filters.priceRange?.max || ''"
          @input="handlePriceMaxChange"
          class="vkecom-product-filters-input"
        />
      </div>

      <div v-if="facets?.categories && facets.categories.length > 0" class="vkecom-product-filters-section">
        <h3>Categories</h3>
        <label
          v-for="category in facets.categories"
          :key="category.id"
          class="vkecom-product-filters-checkbox"
        >
          <input
            type="checkbox"
            :checked="filters.categories?.includes(category.id) || false"
            @change="handleCategoryToggle(category.id)"
          />
          <span>{{ category.name }} ({{ category.count }})</span>
        </label>
      </div>

      <div v-if="facets?.tags && facets.tags.length > 0" class="vkecom-product-filters-section">
        <h3>Tags</h3>
        <label
          v-for="tagItem in facets.tags"
          :key="tagItem.tag"
          class="vkecom-product-filters-checkbox"
        >
          <input
            type="checkbox"
            :checked="filters.tags?.includes(tagItem.tag) || false"
            @change="handleTagToggle(tagItem.tag)"
          />
          <span>{{ tagItem.tag }} ({{ tagItem.count }})</span>
        </label>
      </div>

      <div class="vkecom-product-filters-section">
        <label class="vkecom-product-filters-checkbox">
          <input
            type="checkbox"
            :checked="filters.inStock === true"
            @change="handleStockToggle"
          />
          <span>In Stock Only</span>
        </label>
      </div>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { ProductFilter } from '@alejandrovrod/blocks-core';

interface Props {
  filters: ProductFilter;
  facets?: {
    categories?: Array<{ id: string; name: string; count: number }>;
    priceRanges?: Array<{ min: number; max: number; count: number }>;
    tags?: Array<{ tag: string; count: number }>;
  };
  onChange: (filters: ProductFilter) => void;
  className?: string;
}

const props = defineProps<Props>();

const handlePriceMinChange = (e: Event) => {
  const target = e.target as HTMLInputElement;
  props.onChange({
    ...props.filters,
    priceRange: {
      min: target.value ? parseFloat(target.value) : undefined,
      max: props.filters.priceRange?.max,
    },
  });
};

const handlePriceMaxChange = (e: Event) => {
  const target = e.target as HTMLInputElement;
  props.onChange({
    ...props.filters,
    priceRange: {
      min: props.filters.priceRange?.min,
      max: target.value ? parseFloat(target.value) : undefined,
    },
  });
};

const handleCategoryToggle = (categoryId: string) => {
  const currentCategories = props.filters.categories || [];
  const newCategories = currentCategories.includes(categoryId)
    ? currentCategories.filter((id) => id !== categoryId)
    : [...currentCategories, categoryId];
  
  props.onChange({
    ...props.filters,
    categories: newCategories.length > 0 ? newCategories : undefined,
  });
};

const handleTagToggle = (tag: string) => {
  const currentTags = props.filters.tags || [];
  const newTags = currentTags.includes(tag)
    ? currentTags.filter((t) => t !== tag)
    : [...currentTags, tag];
  
  props.onChange({
    ...props.filters,
    tags: newTags.length > 0 ? newTags : undefined,
  });
};

const handleStockToggle = () => {
  props.onChange({
    ...props.filters,
    inStock: props.filters.inStock === true ? undefined : true,
  });
};
</script>

// packages/blocks-react/src/products/ProductFilters.tsx
/**
 * Product filters component
 */

import React from 'react';
import type { ProductFilter } from '@alejandrovrod/blocks-core';

export interface ProductFiltersProps {
  /**
   * Current filters
   */
  filters: ProductFilter;
  
  /**
   * Available facets (for filter options)
   */
  facets?: {
    categories?: Array<{ id: string; name: string; count: number }>;
    priceRanges?: Array<{ min: number; max: number; count: number }>;
    tags?: Array<{ tag: string; count: number }>;
  };
  
  /**
   * On filters change callback
   */
  onChange?: (filters: ProductFilter) => void;
  
  /**
   * Alias for onChange (for compatibility)
   */
  onFiltersChange?: (filters: ProductFilter) => void;
  
  /**
   * Custom class name
   */
  className?: string;
  
  /**
   * Custom render for filter section
   */
  renderFilters?: (props: {
    filters: ProductFilter;
    facets: ProductFiltersProps['facets'];
    onChange: (filters: ProductFilter) => void;
  }) => React.ReactNode;
  
  /**
   * Children (for custom content)
   */
  children?: React.ReactNode;
}

export function ProductFilters({
  filters,
  facets,
  onChange,
  onFiltersChange,
  className,
  renderFilters,
  children,
}: ProductFiltersProps) {
  const handleChange = onFiltersChange || onChange || (() => {});
  const handlePriceRangeChange = (min?: number, max?: number) => {
    handleChange({
      ...filters,
      priceRange: { min, max },
    });
  };

  const handleCategoryToggle = (categoryId: string) => {
    const currentCategories = filters.categories || [];
    const newCategories = currentCategories.includes(categoryId)
      ? currentCategories.filter((id) => id !== categoryId)
      : [...currentCategories, categoryId];
    
    handleChange({
      ...filters,
      categories: newCategories.length > 0 ? newCategories : undefined,
    });
  };

  const handleTagToggle = (tag: string) => {
    const currentTags = filters.tags || [];
    const newTags = currentTags.includes(tag)
      ? currentTags.filter((t) => t !== tag)
      : [...currentTags, tag];
    
    handleChange({
      ...filters,
      tags: newTags.length > 0 ? newTags : undefined,
    });
  };

  const handleStockToggle = (inStock: boolean) => {
    handleChange({
      ...filters,
      inStock: filters.inStock === inStock ? undefined : inStock,
    });
  };

  if (children) {
    return <div className={`vkecom-product-filters ${className || ''}`}>{children}</div>;
  }

  if (renderFilters) {
    return (
      <div className={`vkecom-product-filters ${className || ''}`}>
        {renderFilters({ filters, facets, onChange: handleChange })}
      </div>
    );
  }

  return (
    <div className={`vkecom-product-filters ${className || ''}`}>
      <div className="vkecom-product-filters-section">
        <h3>Price Range</h3>
        <input
          type="number"
          placeholder="Min"
          value={filters.priceRange?.min || ''}
          onChange={(e) => handlePriceRangeChange(
            e.target.value ? parseFloat(e.target.value) : undefined,
            filters.priceRange?.max
          )}
          className="vkecom-product-filters-input"
        />
        <input
          type="number"
          placeholder="Max"
          value={filters.priceRange?.max || ''}
          onChange={(e) => handlePriceRangeChange(
            filters.priceRange?.min,
            e.target.value ? parseFloat(e.target.value) : undefined
          )}
          className="vkecom-product-filters-input"
        />
      </div>

      {facets?.categories && facets.categories.length > 0 && (
        <div className="vkecom-product-filters-section">
          <h3>Categories</h3>
          {facets.categories.map((category) => (
            <label key={category.id} className="vkecom-product-filters-checkbox">
              <input
                type="checkbox"
                checked={filters.categories?.includes(category.id) || false}
                onChange={() => handleCategoryToggle(category.id)}
              />
              <span>{category.name} ({category.count})</span>
            </label>
          ))}
        </div>
      )}

      {facets?.tags && facets.tags.length > 0 && (
        <div className="vkecom-product-filters-section">
          <h3>Tags</h3>
          {facets.tags.map((tagItem) => (
            <label key={tagItem.tag} className="vkecom-product-filters-checkbox">
              <input
                type="checkbox"
                checked={filters.tags?.includes(tagItem.tag) || false}
                onChange={() => handleTagToggle(tagItem.tag)}
              />
              <span>{tagItem.tag} ({tagItem.count})</span>
            </label>
          ))}
        </div>
      )}

      <div className="vkecom-product-filters-section">
        <label className="vkecom-product-filters-checkbox">
          <input
            type="checkbox"
            checked={filters.inStock === true}
            onChange={() => handleStockToggle(true)}
          />
          <span>In Stock Only</span>
        </label>
      </div>
    </div>
  );
}
