// packages/blocks-angular/src/products/product-filters.component.ts
/**
 * Product filters component
 */

import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import type { ProductFilter } from '@vk/blocks-core';

@Component({
  selector: 'vk-product-filters',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div [class]="'vkecom-product-filters ' + (className || '')">
      <div class="vkecom-product-filters-section">
        <h3>Price Range</h3>
        <input
          type="number"
          placeholder="Min"
          [value]="filters.priceRange?.min || ''"
          (input)="handlePriceMinChange($event)"
          class="vkecom-product-filters-input"
        />
        <input
          type="number"
          placeholder="Max"
          [value]="filters.priceRange?.max || ''"
          (input)="handlePriceMaxChange($event)"
          class="vkecom-product-filters-input"
        />
      </div>

      <div
        *ngIf="facets?.categories && facets.categories.length > 0"
        class="vkecom-product-filters-section"
      >
        <h3>Categories</h3>
        <label
          *ngFor="let category of facets.categories"
          class="vkecom-product-filters-checkbox"
        >
          <input
            type="checkbox"
            [checked]="filters.categories?.includes(category.id) || false"
            (change)="handleCategoryToggle(category.id)"
          />
          <span>{{ category.name }} ({{ category.count }})</span>
        </label>
      </div>

      <div
        *ngIf="facets?.tags && facets.tags.length > 0"
        class="vkecom-product-filters-section"
      >
        <h3>Tags</h3>
        <label *ngFor="let tagItem of facets.tags" class="vkecom-product-filters-checkbox">
          <input
            type="checkbox"
            [checked]="filters.tags?.includes(tagItem.tag) || false"
            (change)="handleTagToggle(tagItem.tag)"
          />
          <span>{{ tagItem.tag }} ({{ tagItem.count }})</span>
        </label>
      </div>

      <div class="vkecom-product-filters-section">
        <label class="vkecom-product-filters-checkbox">
          <input
            type="checkbox"
            [checked]="filters.inStock === true"
            (change)="handleStockToggle()"
          />
          <span>In Stock Only</span>
        </label>
      </div>
    </div>
  `,
})
export class ProductFiltersComponent {
  @Input() filters!: ProductFilter;
  @Input() facets?: {
    categories?: Array<{ id: string; name: string; count: number }>;
    priceRanges?: Array<{ min: number; max: number; count: number }>;
    tags?: Array<{ tag: string; count: number }>;
  };
  @Output() change = new EventEmitter<ProductFilter>();
  @Input() className?: string;

  handlePriceMinChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.change.emit({
      ...this.filters,
      priceRange: {
        min: target.value ? parseFloat(target.value) : undefined,
        max: this.filters.priceRange?.max,
      },
    });
  }

  handlePriceMaxChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.change.emit({
      ...this.filters,
      priceRange: {
        min: this.filters.priceRange?.min,
        max: target.value ? parseFloat(target.value) : undefined,
      },
    });
  }

  handleCategoryToggle(categoryId: string): void {
    const currentCategories = this.filters.categories || [];
    const newCategories = currentCategories.includes(categoryId)
      ? currentCategories.filter((id) => id !== categoryId)
      : [...currentCategories, categoryId];

    this.change.emit({
      ...this.filters,
      categories: newCategories.length > 0 ? newCategories : undefined,
    });
  }

  handleTagToggle(tag: string): void {
    const currentTags = this.filters.tags || [];
    const newTags = currentTags.includes(tag)
      ? currentTags.filter((t) => t !== tag)
      : [...currentTags, tag];

    this.change.emit({
      ...this.filters,
      tags: newTags.length > 0 ? newTags : undefined,
    });
  }

  handleStockToggle(): void {
    this.change.emit({
      ...this.filters,
      inStock: this.filters.inStock === true ? undefined : true,
    });
  }
}


<div [class]="'vkecom-product-filters ' + (className || '')">
  <div class="vkecom-product-filters-section">
    <h3>Price Range</h3>
    <input
      type="number"
      placeholder="Min"
      [value]="filters.priceRange?.min || ''"
      (input)="handlePriceMinChange($event)"
      class="vkecom-product-filters-input"
    />
    <input
      type="number"
      placeholder="Max"
      [value]="filters.priceRange?.max || ''"
      (input)="handlePriceMaxChange($event)"
      class="vkecom-product-filters-input"
    />
  </div>

  <div
    *ngIf="facets?.categories && facets.categories.length > 0"
    class="vkecom-product-filters-section"
  >
    <h3>Categories</h3>
    <label
      *ngFor="let category of facets.categories"
      class="vkecom-product-filters-checkbox"
    >
      <input
        type="checkbox"
        [checked]="filters.categories?.includes(category.id) || false"
        (change)="handleCategoryToggle(category.id)"
      />
      <span>{{ category.name }} ({{ category.count }})</span>
    </label>
  </div>

  <div
    *ngIf="facets?.tags && facets.tags.length > 0"
    class="vkecom-product-filters-section"
  >
    <h3>Tags</h3>
    <label *ngFor="let tagItem of facets.tags" class="vkecom-product-filters-checkbox">
      <input
        type="checkbox"
        [checked]="filters.tags?.includes(tagItem.tag) || false"
        (change)="handleTagToggle(tagItem.tag)"
      />
      <span>{{ tagItem.tag }} ({{ tagItem.count }})</span>
    </label>
  </div>

  <div class="vkecom-product-filters-section">
    <label class="vkecom-product-filters-checkbox">
      <input
        type="checkbox"
        [checked]="filters.inStock === true"
        (change)="handleStockToggle()"
      />
      <span>In Stock Only</span>
    </label>
  </div>
</div>

// packages/blocks-vue/src/products/ProductFilters.vue
<template>
  <div :class="['vkecom-product-filters', className]">
    <slot name="filters" :filters="filters" :facets="facets" :on-change="onChange">
      <div class="vkecom-product-filters-section">
        <h3>Price Range</h3>
        <input
          type="number"
          placeholder="Min"
          :value="filters.priceRange?.min || ''"
          @input="handlePriceMinChange"
          class="vkecom-product-filters-input"
        />
        <input
          type="number"
          placeholder="Max"
          :value="filters.priceRange?.max || ''"
          @input="handlePriceMaxChange"
          class="vkecom-product-filters-input"
        />
      </div>

      <div v-if="facets?.categories && facets.categories.length > 0" class="vkecom-product-filters-section">
        <h3>Categories</h3>
        <label
          v-for="category in facets.categories"
          :key="category.id"
          class="vkecom-product-filters-checkbox"
        >
          <input
            type="checkbox"
            :checked="filters.categories?.includes(category.id) || false"
            @change="handleCategoryToggle(category.id)"
          />
          <span>{{ category.name }} ({{ category.count }})</span>
        </label>
      </div>

      <div v-if="facets?.tags && facets.tags.length > 0" class="vkecom-product-filters-section">
        <h3>Tags</h3>
        <label
          v-for="tagItem in facets.tags"
          :key="tagItem.tag"
          class="vkecom-product-filters-checkbox"
        >
          <input
            type="checkbox"
            :checked="filters.tags?.includes(tagItem.tag) || false"
            @change="handleTagToggle(tagItem.tag)"
          />
          <span>{{ tagItem.tag }} ({{ tagItem.count }})</span>
        </label>
      </div>

      <div class="vkecom-product-filters-section">
        <label class="vkecom-product-filters-checkbox">
          <input
            type="checkbox"
            :checked="filters.inStock === true"
            @change="handleStockToggle"
          />
          <span>In Stock Only</span>
        </label>
      </div>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { ProductFilter } from '@vk/blocks-core';

interface Props {
  filters: ProductFilter;
  facets?: {
    categories?: Array<{ id: string; name: string; count: number }>;
    priceRanges?: Array<{ min: number; max: number; count: number }>;
    tags?: Array<{ tag: string; count: number }>;
  };
  onChange: (filters: ProductFilter) => void;
  className?: string;
}

const props = defineProps<Props>();

const handlePriceMinChange = (e: Event) => {
  const target = e.target as HTMLInputElement;
  props.onChange({
    ...props.filters,
    priceRange: {
      min: target.value ? parseFloat(target.value) : undefined,
      max: props.filters.priceRange?.max,
    },
  });
};

const handlePriceMaxChange = (e: Event) => {
  const target = e.target as HTMLInputElement;
  props.onChange({
    ...props.filters,
    priceRange: {
      min: props.filters.priceRange?.min,
      max: target.value ? parseFloat(target.value) : undefined,
    },
  });
};

const handleCategoryToggle = (categoryId: string) => {
  const currentCategories = props.filters.categories || [];
  const newCategories = currentCategories.includes(categoryId)
    ? currentCategories.filter((id) => id !== categoryId)
    : [...currentCategories, categoryId];
  
  props.onChange({
    ...props.filters,
    categories: newCategories.length > 0 ? newCategories : undefined,
  });
};

const handleTagToggle = (tag: string) => {
  const currentTags = props.filters.tags || [];
  const newTags = currentTags.includes(tag)
    ? currentTags.filter((t) => t !== tag)
    : [...currentTags, tag];
  
  props.onChange({
    ...props.filters,
    tags: newTags.length > 0 ? newTags : undefined,
  });
};

const handleStockToggle = () => {
  props.onChange({
    ...props.filters,
    inStock: props.filters.inStock === true ? undefined : true,
  });
};
</script>
